USE GS_FACT_03;
GO

--CREACION DE LA TABLA CON VALORES POR DEFECTO
CREATE TABLE EMPRESA(
    ID_EMPRESA INT IDENTITY,
    NOMBRE VARCHAR(20) DEFAULT 'AC. REDES',
    DESCRIPCION_EMPRESA VARCHAR (60) DEFAULT 'EMPRESA DESTINADA A GESTIONAR SISTEMAS DE FACTURACION PARA TU NEGOCIO'
);
