USE GS_FACT_03;
GO

--CREACION DE LA TABLA
CREATE TABLE FACTURA(
	     ID_FACTURA int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	     ID_EMPRESA int DEFAULT 1 NOT NULL,
	     ID_CLIENTE int NOT NULL,
	     FECHA_FACTURACION date NOT NULL,
	     ESTADO varchar(30) DEFAULT 'PAGADO' NOT NULL
);

