USE GS_FACT_03;
GO

--CREACION DE LA TABLA
CREATE TABLE FACTURA(
	     ID_FACTURA int IDENTITY(1,1) PRIMARY KEY NOT NULL,
	     ID_EMPRESA int DEFAULT 1 NOT NULL,
	     ID_CLIENTE int NOT NULL,
	     FECHA_FACTURACION date NOT NULL,
	     ESTADO varchar(30) DEFAULT 'PAGADO' NOT NULL
);

--primary key
ALTER TABLE FACTURA ADD CONSTRAINT ID_FACT PRIMARY KEY(ID_FACTURA);

--FOREIGN KEY
ALTER TABLE FACTURA ADD CONSTRAINT FK_idEmpresa FOREIGN KEY (ID_EMPRESA) REFERENCES EMPRESA(ID_EMPRESA) ON DELETE CASCADE;
ALTER TABLE FACTURA ADD CONSTRAINT FK_idCliente FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE;




