CREATE TABLE DETALLE_FACTURA(
	ID_DETALLE_FACTURA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_SERVICIO INT NOT NULL,
	NOMBRE_ENCARGADO VARCHAR(80) NOT NULL,
	CANTIDAD INT DEFAULT 1 NOT NULL,
	TOTAL_PAGAR FLOAT
);

--PRIMARY KEY
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT idDetFact_PK PRIMARY KEY (ID_DETALLE_FACTURA);

--FOREIGN KEY
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_idFact FOREIGN KEY (ID_FACTURA) REFERENCES FACTURA(ID_FACTURA) ON DELETE CASCADE;
ALTER TABLE DETALLE_FACTURA ADD CONSTRAINT FK_idServ FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO) ON DELETE CASCADE;
