USE GS_FACT_03;
GO

CREATE TABLE REEMBOLSO(
	ID_REEMBOLSO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	ID_FACTURA INT NOT NULL,
	ID_SERVICIO INT NOT NULL,
	MOTIVO_REEMBOLSO VARCHAR(180) DEFAULT 'NO ESPECIFICADO',
	FECHA DATE NOT NULL
);