USE GS_FACT_03;
GO

--CREACION DE LA TABLA CON VALORES POR DEFECTO
CREATE TABLE EMPRESA(
    ID_EMPRESA INT IDENTITY(1,1),
    NOMBRE VARCHAR(20) DEFAULT 'AC. REDES',
    DESCRIPCION_EMPRESA VARCHAR (180) DEFAULT 'EMPRESA DESTINADA A GESTIONAR SISTEMAS DE FACTURACION PARA TU NEGOCIO'
);

ALTER TABLE EMPRESA ADD CONSTRAINT idEmpresa_PK PRIMARY KEY(ID_EMPRESA);
