USE GS_FACT_03;
GO

CREATE TABLE SERVICIO(
	ID_SERVICIO INT IDENTITY (1,1)PRIMARY KEY NOT NULL,
	DESCRIPCION_SERVICIO VARCHAR(180) DEFAULT 'SIN ESPECIFICAR',
	VALOR_UNITARIO FLOAT
);

ALTER TABLE SERVICIO ADD CONSTRAINT ID_SERVICIO_PK PRIMARY KEY (ID_SERVICIO);
